const PERMISSIONS = require('./permissions');

const ROLE_PERMISSIONS = {
    "SUPER-ADMIN": Object.values(PERMISSIONS),
    "ADMIN": Object.values(PERMISSIONS),
    "MANAGER": [
        PERMISSIONS.CREATE_STAFF,
        PERMISSIONS.ADD_FINANCE,
        PERMISSIONS.EDIT_FINANCE,
        PERMISSIONS.UPLOAD_DOCUMENT,
        PERMISSIONS.CREATE_VEHICLE,
        PERMISSIONS.EDIT_VEHICLE,
        PERMISSIONS.VIEW_REPORTS,
        PERMISSIONS.ASSIGN_DELIVERY,
        PERMISSIONS.UPDATE_INVENTORY
    ],
    "SHOWROOM-STAFF": [
        PERMISSIONS.ADD_FINANCE,
        PERMISSIONS.UPLOAD_DOCUMENT,
        PERMISSIONS.VIEW_REPORTS
    ],
    "DELIVERY-BOY-DRIVER": [
        PERMISSIONS.UPDATE_DELIVERY
    ],
    "DELIVERY-BOY": [
        PERMISSIONS.UPDATE_DELIVERY
    ],
    "MECHANIC": [
        PERMISSIONS.UPDATE_DELIVERY // Assuming similar task or none
    ],
    "GODOWN-KEEPER": [
        PERMISSIONS.UPDATE_INVENTORY,
        PERMISSIONS.VIEW_REPORTS
    ],
    "TRUCK-DRIVER": [
        PERMISSIONS.UPDATE_DELIVERY
    ]
};

module.exports = ROLE_PERMISSIONS;
